on:
  issues:
    types: [opened] # change to "locked"?

jobs:

  run-direct-report-on-issue:
    if: contains(github.event.issue.labels.*.name, 'direct_ann_to_list_of_terms')
    runs-on: ubuntu-22.04
    name: Add issue comment
    steps:
      - name: Proof of env
        env:
          NUMBER: ${{ github.event.issue.number }}
        run: |
          echo A comment on issue $NUMBER
      - name: Checkout this repo
        uses: actions/checkout@v2
        with:
          ref: ${{ github.head_ref }}
      - name: Run main annotation script
        env:
          NUMBER: ${{ github.event.issue.number }}
        run: mkdir -p reports/$NUMBER && python3 ./scripts/annotation-review-report.py geneontology/go-annotation 7 --number $NUMBER --label direct_ann_to_list_of_terms --field annotation_class --output ./reports/$NUMBER --verbose
      - name: Run extensions annotation script
        env:
          NUMBER: ${{ github.event.issue.number }}
        run: mkdir -p reports/$NUMBER && python3 ./scripts/annotation-review-report.py geneontology/go-annotation 7 --number $NUMBER --label direct_ann_to_list_of_terms --field annotation_extension_class --output ./reports/$NUMBER --prefix extensions --verbose
      - name: Run evidence_with annotation script
        env:
          NUMBER: ${{ github.event.issue.number }}
        run: mkdir -p reports/$NUMBER && python3 ./scripts/annotation-review-report.py geneontology/go-annotation 7 --number $NUMBER --label direct_ann_to_list_of_terms --field evidence_with --output ./reports/$NUMBER --prefix ev_with --verbose
      - name: Run mapping hit script
        env:
          NUMBER: ${{ github.event.issue.number }}
        run: mkdir -p reports/$NUMBER && wget --recursive --no-parent http://snapshot.geneontology.org/ontology/external2go/ && rm -f snapshot.geneontology.org/ontology/external2go/README.md snapshot.geneontology.org/ontology/external2go/index.html snapshot.geneontology.org/ontology/external2go/pfam2go snapshot.geneontology.org/ontology/external2go/pirsf2go snapshot.geneontology.org/ontology/external2go/prints2go snapshot.geneontology.org/ontology/external2go/prodom2go snapshot.geneontology.org/ontology/external2go/prosite2go snapshot.geneontology.org/ontology/external2go/smart2go && python3 ./scripts/mapping-report.py geneontology/go-annotation 7 --number $NUMBER --label direct_ann_to_list_of_terms --input ./snapshot.geneontology.org/ontology/external2go/ --output ./reports/$NUMBER --verbose && rm -f snapshot.geneontology.org/ontology/external2go/*2go && rmdir snapshot.geneontology.org/ontology/external2go && snapshot.geneontology.org/ontology && snapshot.geneontology.org
      - name: Commit reports back to main
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: |
            Reports at https://github.com/geneontology/go-annotation/tree/master/reports/${{ github.event.issue.number }} for issue https://github.com/geneontology/go-annotation/issues/${{ github.event.issue.number }}
          commit_user_email: sjcarbon@lbl.gov
          # Please do the dirty check, don't skip
          skip_dirty_check: false
